<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <SpaRoot>.\</SpaRoot>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

</Project>
